# Generated by Django 6.0.6 on 2026-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_comment_options_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='comments/audio/', verbose_name='Voice Message'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Content'),
        ),
    ]
