# Generated by Django 6.0.6 on 2026-06-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_comment_audio_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(verbose_name='测量时间')),
                ('weight_jin', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='体重(斤)')),
                ('bmi', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='BMI')),
                ('body_fat_pct', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='体脂率(%)')),
                ('body_fat_score', models.IntegerField(blank=True, null=True, verbose_name='体脂得分')),
                ('skeletal_muscle_jin', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='骨骼肌量(斤)')),
                ('visceral_fat_level', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='内脏脂肪等级')),
                ('arms_legs_muscle_index', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='四肢骨骼肌指数(kg/m²)')),
                ('waist_hip_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='推测腰臀比')),
                ('body_water_pct', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='水分率(%)')),
                ('protein_pct', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='蛋白质(%)')),
                ('bone_mineral_jin', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='骨盐量(斤)')),
                ('fat_free_mass_jin', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='去脂体重(斤)')),
                ('basal_metabolism_kcal', models.IntegerField(verbose_name='基础代谢(千卡/日)')),
                ('body_age', models.IntegerField(verbose_name='身体年龄')),
                ('heart_rate', models.IntegerField(verbose_name='心率(次/分)')),
                ('body_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='体型类型')),
                ('body_shape', models.CharField(blank=True, max_length=50, null=True, verbose_name='体形态')),
                ('bmi_change', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='BMI变化')),
                ('body_fat_change', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体脂率变化(%)')),
                ('skeletal_muscle_change', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='骨骼肌变化(斤)')),
                ('body_water_change', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='水分率变化(%)')),
                ('fat_free_mass_change', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='去脂体重变化(斤)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录创建时间')),
            ],
            options={
                'verbose_name': '体重测量',
                'verbose_name_plural': '体重测量数据',
                'ordering': ['-measured_at'],
            },
        ),
    ]
