# Generated by Django 6.0.6 on 2026-06-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bodymeasurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodymeasurement',
            name='basal_metabolism_kcal',
            field=models.IntegerField(blank=True, null=True, verbose_name='基础代谢(千卡/日)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='身体年龄'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_fat_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体脂率(%)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='body_water_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='水分率(%)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='bone_mineral_jin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='骨盐量(斤)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='fat_free_mass_jin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='去脂体重(斤)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='心率(次/分)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='protein_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='蛋白质(%)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='skeletal_muscle_jin',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='骨骼肌量(斤)'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='visceral_fat_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='内脏脂肪等级'),
        ),
        migrations.AlterField(
            model_name='bodymeasurement',
            name='weight_jin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='体重(斤)'),
        ),
    ]
