"""Generate 300 English joke posts."""
import os, random, django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'web_project.settings')
django.setup()

from django.contrib.auth.models import User
from accounts.models import Post

author = User.objects.get(username='admin')
random.seed(2027)

# ── English joke title templates (each 16-50 chars) ──────────────
title_templates = [
    "Hilarious Office Jokes That Will Make You Cry Laughing",
    "The Funniest School Stories Ever Told",
    "Classic Husband and Wife Comedy Moments",
    "Programmer Humor Only Coders Will Understand",
    "Doctor and Patient Funny Conversations",
    "Teacher and Student Comedy Gold",
    "The Most Awkward Dating App Encounters",
    "Ridiculous Things That Happened on Public Transport",
    "Gym Fails That Are Too Funny to Handle",
    "Restaurant Blunders and Waiter Comebacks",
    "Hilarious Things Kids Say to Their Parents",
    "The Best Barber Shop Conversations Ever",
    "Airport and Travel Misadventures Collection",
    "Grocery Store Encounters Gone Wrong",
    "The Funniest Job Interview Responses",
    "Christmas Party Disaster Stories",
    "Wedding Speeches That Went Hilariously Wrong",
    "Neighbor Shenanigans You Won't Believe",
    "Pet Owners and Their Crazy Animal Antics",
    "The Most Ridiculous Customer Complaints",
    "Camping Trips Gone Completely Wrong",
    "Fatherhood Fails Every Dad Will Relate To",
    "Roommate Horror Stories With a Funny Twist",
    "Technology Fails Your Grandma Would Understand",
    "The Funniest Courtroom Exchange Stories",
    "Fitness Trainer and Client Comedy Moments",
    "Driving Test Disasters That Are Too Funny",
    "Elevator Encounters That Got Really Awkward",
    "The Best Comebacks from Customer Service",
    "Holiday Dinner Arguments Gone Hilarious",
    "Sibling Rivalry Stories That Are Pure Comedy",
    "The Funniest Things Overheard in Coffee Shops",
    "Library and Bookstore Quiet Chaos Stories",
    "Hotel Reception Desk Comedy Moments",
    "Movie Theater Shenanigans That Stole the Show",
    "Birthday Party Blunders Worth Celebrating",
    "The Most Awkward Video Call Moments Ever",
    "Online Shopping Reviews That Went Viral",
    "Dentist Office Jokes to Numb the Pain",
    "Picnic Disasters That Ended in Laughter",
]

# ── English joke content pool ────────────────────────────────────
jokes = []

def add(text):
    jokes.append(text)

add('A man walks into a bar and orders a drink. The bartender asks, "Why the long face?" The man replies, "I just found out my wife is cheating on me with my best friend." The bartender says, "That\'s terrible! What are you going to do?" The man sighs and says, "Well, I\'m going to tell her I know. Then I\'m going to tell my best friend I know." The bartender asks, "And then what?" The man looks up and says, "Then I\'m going to need a new best friend... and probably a new wife. You know anybody hiring?" The bartender pours him a double. "Buddy, with that story, this one\'s on the house."')

add('A teacher asks her class, "If I have 5 apples in one hand and 6 apples in the other, what do I have?" Little Johnny raises his hand immediately. "Yes, Johnny?" Johnny grins and says, "Really big hands, Miss!" The teacher sighs while the entire classroom erupts in laughter. She tries again: "Alright Johnny, if I gave you 2 rabbits and then gave you 3 more rabbits, how many rabbits would you have?" Johnny thinks for a moment. "Seven rabbits, Miss." The teacher beams with pride. "That\'s correct! How did you figure that out?" Johnny shrugs: "Because you can\'t give me just one rabbit — they multiply. I learned that from my dad\'s spreadsheet." The teacher decided to move on to geography.')

add('Two programmers are debugging a piece of code late at night. Programmer A: "I found the bug! It was a missing semicolon on line 247." Programmer B: "That\'s impossible, I checked that line ten times." Programmer A: "Well, it\'s fixed now. Let\'s commit and go home." They commit the code and leave. The next morning, they come back to find the entire system is down. They spend four hours debugging only to discover that Programmer A had accidentally added an extra semicolon on line 246 while removing the other one. Programmer B stares at the screen and whispers, "It wasn\'t a bug fix. It was a bug migration program." Neither of them spoke for the rest of the day.')

add('A wife asks her husband, "Do you think I\'m pretty or ugly?" Without looking up from his phone, the husband says, "You\'re both." The wife\'s eyes narrow. "What do you mean, both?" The husband finally looks up, realizing he\'s in trouble. He quickly adds, "I mean, you\'re pretty... ugly... wait, no! That came out wrong!" He scrambles for words. "What I meant was — you\'re so pretty it\'s ugly how other women must feel when they see you!" The wife crosses her arms. "Nice save." The husband wipes sweat from his forehead. "Thanks, I\'ve been practicing in the mirror." The wife sighs. "Clearly not enough."')

add('A job interviewer asks the candidate, "Where do you see yourself in five years?" The candidate leans back thoughtfully and says, "Well, ideally, I\'d like to be in your position — interviewing people and asking them ridiculous questions while pretending I have my life together." The interviewer stares blankly. The candidate continues: "But more realistically, I\'ll probably be sitting in this exact same chair, applying for this exact same job, because the economy is unpredictable and I make poor life choices." The interviewer closes their notebook. "Honesty. I appreciate that." The candidate asks, "So do I get the job?" The interviewer replies, "Honestly? No. But I\'ll remember you forever."')

add('A little boy asks his grandfather, "Grandpa, can you make frog sounds?" The grandfather, confused, asks, "Why do you want to know?" The little boy replies, "Because Grandma said that when you croak, we\'re all going to Hawaii!" The grandfather storms into the kitchen where Grandma is cooking. "Did you tell little Timmy that when I croak, you\'re all going to Hawaii?" Grandma doesn\'t miss a beat. "Of course I did, dear. It\'s called motivation. Now go take your vitamins."')

add('A man is on his first date with a woman he met online. She asks, "So, what are your hobbies?" The man, trying to sound interesting, says, "I collect rare coins, I restore vintage motorcycles, and I volunteer at an animal shelter on weekends." The woman looks impressed. "Wow, that\'s amazing! What else?" The man, now completely committed to the lie, says, "I also speak three languages." The woman\'s eyes light up. "Really? Which ones?" The man freezes. "English, bad English, and... typing sounds with my mouth." He then proceeds to make modem noises. Surprisingly, they\'ve been married for three years now, and he still makes the modem noises every anniversary.')

add('A passenger on a flight asks the flight attendant, "Excuse me, how high are we flying right now?" The flight attendant smiles professionally. "About 35,000 feet, sir." The passenger nods and asks, "And how fast are we going?" The flight attendant replies, "Approximately 550 miles per hour." The passenger thinks for a moment. "So if the plane is going 550 miles per hour, and I get up to use the bathroom, am I technically going faster than the plane?" The flight attendant pauses. "Sir, I handle peanuts and seatbelts, not quantum physics. Please sit down."')

add('A man goes to the doctor and says, "Doctor, I think I\'m addicted to Twitter." The doctor replies, "I\'m sorry, I don\'t follow you." They both stared at each other for an awkward five seconds before the doctor realized what just happened. "That was unintentional, I swear," the doctor said. The patient sighed. "That\'s what everyone says on Twitter when their tweet gets ratioed." The doctor wrote in his notes: "Patient\'s condition is worse than I thought. Also, I really need to stop scrolling at work."')

add('An elderly couple is sitting on the porch. The wife turns to the husband and says, "Honey, remember how we used to sit here and just hold hands without saying a word?" The husband nods. "Yeah, those were good times." The wife looks at him expectantly. "Well? Why don\'t we do that anymore?" The husband takes a long sip of his lemonade. "Because now if I let go of this chair, I\'ll fall over. And if you let go of your chair, you\'ll fall over. This isn\'t romance anymore, Margaret. This is structural engineering." Margaret didn\'t speak to him for the rest of the afternoon, but she did tighten the screws on his rocking chair.')

add('A college student emails his professor at 3 AM: "Dear Professor, I was unable to submit my homework because my laptop crashed. Please find attached a screenshot of the blue screen of death as proof." The professor replies at 3:02 AM: "Dear Student, I have carefully reviewed your attached screenshot. After thorough analysis, I have determined that the blue screen of death occurred because you downloaded seven seasons of a TV show and filled your hard drive. I have also determined, through the reflection in your screen, that you are not wearing pants. Your extension is denied. P.S. Please put on some pants."')

add('A guy is at the grocery store buying a single bag of chips, a frozen pizza, and a bottle of wine. The cashier looks at the items and asks, "Single, huh?" The guy looks offended. "No! How could you say that?" The cashier points to the items. "This is the classic lonely Friday night starter pack. I see it at least twenty times per shift." The guy starts to protest but then looks down at his items. He sighs. "You\'re right. But for the record, the chips are for my... cat." The cashier nods solemnly. "Sir, I\'ve been working here for five years. Cats don\'t eat sour cream and onion chips. But I respect your privacy."')

add('A wife tells her husband, "I had a dream last night that you bought me a diamond necklace for our anniversary." The husband, without looking up from his newspaper, says, "That\'s nice, honey." The wife continues, "And then in my dream, you also bought me a brand new sports car." The husband turns a page. "How exciting for dream-me." The wife leans closer. "And then you told me I was the most beautiful woman in the world." The husband finally looks up. "Wow. Dream-me sounds like a really great guy. Have you considered marrying him instead? Because real-me just remembered that our anniversary is actually next month, and I haven\'t bought anything yet." The wife smiles sweetly. "I know. That\'s why I\'m giving you a month of dreams to prepare."')

add('A man walks into a library and aggressively whispers to the librarian, "I NEED A BOOK ON HOW TO CONTROL MY ANGER!" The librarian calmly looks up, adjusts her glasses, and whispers back, "Sir, this is a library. Please lower your voice." The man takes a deep breath and whispers very intensely, "Sorry. Can you please help me find a book on anger management?" The librarian types on her computer for a moment. "It\'s in the self-help section, aisle 4, on your left. But if you can\'t find it, please don\'t get angry — just come back and I\'ll help you look." The man stared at her. "You\'re enjoying this, aren\'t you?" The librarian smiled. "I work in a library, sir. This is the most excitement I\'ve had all week."')

add('A teenage boy asks his dad, "Dad, can I borrow the car tonight?" The dad says, "Sure, but first you have to do three things: get a haircut, improve your grades, and read the Bible cover to cover." The son thinks about it and says, "Okay, I\'ll try." Three months later, the son comes back with a shaved head, straight A\'s, and says, "Dad, I did it. Can I borrow the car now?" The dad looks at him proudly and says, "Son, I\'m impressed. But there\'s one problem — the car was repossessed two months ago because I spent all my money on your sister\'s wedding." The son stared at his dad in disbelief. "So you had me read the entire Bible... for nothing?" The dad shrugged. "Hey, now you know where the phrase \'the Lord giveth and the Lord taketh away\' comes from."')

add('A man is at a restaurant and calls the waiter over. "Excuse me, there\'s a fly in my soup." The waiter peers into the bowl. "Sir, that\'s not a fly. That\'s a crouton shaped like a fly." The man squints at it. "Are you sure? Because croutons don\'t usually have wings." The waiter pulls out a tiny pair of reading glasses and examines the bowl like a forensic scientist. "I can confirm, sir, that this is a winged crouton. It\'s a new recipe. Very organic." The man pushes the bowl away. "Fine. Can I just get a new soup without any... airborne bakery products?" The waiter nods solemnly and writes in his notepad, "Table 4: allergic to flying carbohydrates."')

add('A programmer\'s wife sends him to the grocery store with a list: "Buy a loaf of bread. If they have eggs, buy a dozen." The programmer comes back with twelve loaves of bread. His wife stares at the mountain of bread on the kitchen counter. "Why did you buy twelve loaves of bread?!" she shouts. The programmer, genuinely confused, says, "They had eggs." This story has since become a legendary example in every programming class about why you should never write ambiguous requirements and why the phrase "if they have eggs" is functionally equivalent to writing a bug into your marriage.')

add('A man calls his doctor\'s office and says, "I need to schedule an appointment. I think I\'m becoming a moth." The receptionist says, "Sir, you want a psychiatrist, not a general practitioner." The man replies, "I know, but your light was on." There was a long pause. The receptionist finally responded, "Sir, I have been working here for fifteen years. I have heard every possible reason for an appointment. But I have to admit — that is the first time someone has given me a legitimate reason for choosing our clinic over another one. The doctor will see you at 3 PM. Please don\'t fly into the ceiling light on your way in."')

add('A father is teaching his son how to fish. The son asks, "Dad, how do fish breathe underwater?" The father replies, "They have gills, son." The son thinks for a moment. "So if I had gills, I could breathe underwater too?" The father nods. "Technically, yes." The son looks at the water and then back at his father. "Dad, why don\'t humans have gills?" The father, losing patience, says, "Because if humans had gills, you would have asked me why we don\'t have wings, and then I would have to explain aerodynamics to a seven-year-old while trying to catch dinner. Now please be quiet so the fish can\'t hear us." The son paused. "Fish can hear?" The father dropped his fishing rod into the lake.')

add('A woman is at the airport security checkpoint. The TSA agent asks, "Ma\'am, did you pack this bag yourself?" The woman replies, "Yes, I did." The agent asks, "Are you carrying any liquids over three ounces?" The woman shakes her head. "No." The agent then asks, "Did anyone give you anything to carry on the plane?" The woman thinks and says, "Well, my mother-in-law gave me a lot of emotional baggage, but I don\'t think that fits in the overhead compartment." The TSA agent, without missing a beat, says, "Ma\'am, emotional baggage doesn\'t have a size restriction. You can carry as much as you want. Please proceed to your gate, and maybe consider upgrading to first class — you\'ve earned it."')

add('A husband asks his wife, "What do you want for dinner?" She says, "I don\'t know. You decide." He suggests, "How about pizza?" She frowns. "We had pizza last week." He tries again. "Burgers?" She shakes her head. "Too greasy." He thinks harder. "Chinese food?" She sighs. "I\'m not in the mood for Chinese." He throws his hands up. "Then what do you want?" She looks at him with a straight face and says, "I want you to magically know what I want without me having to tell you. Is that so hard?" The husband opens his phone, orders pizza anyway, and says, "I\'ve decided to be a mind reader. Your mind is telling me you want pizza. The mind wants what the mind wants." She ate three slices out of spite. It was the best dinner they\'d had in weeks.')

add('A man sees his neighbor searching frantically under a streetlight. He asks, "What are you looking for?" The neighbor replies, "My car keys. I dropped them somewhere over there in the dark." The man asks, "Then why are you looking here?" The neighbor explains, "Because the light is better here." The man stares at him for a long moment. "You know that\'s not how finding things works, right?" The neighbor stands up and dusts off his knees. "Listen, I\'ve been looking for my keys for twenty minutes. I\'ve tried logic. Logic didn\'t work. Now I\'m trying whatever works. If you\'re not going to help, at least don\'t judge my process." The man shrugged, went home, and found his neighbor\'s keys in his own coat pocket. He never returned them, because some lessons can only be learned the hard way.')

add('A student raises his hand in class. "Mr. Johnson, would you punish me for something I didn\'t do?" The teacher replies, "Of course not. That wouldn\'t be fair." The student grins. "Good, because I didn\'t do my homework." The teacher removes his glasses and rubs his eyes slowly. "That\'s a clever trap, Kevin. But you forgot one thing." Kevin looks nervous. "What?" The teacher pulls out a detention slip. "You DID do something — you tried to outsmart your teacher in front of the entire class. That\'s a punishable offense. Two birds, one detention slip." Kevin received detention for one week. More importantly, he received his classmates\' respect for even attempting it.')

add('A boss calls an employee into his office. "I\'ve noticed you\'ve been taking very long lunch breaks lately. Care to explain?" The employee says, "Sir, I\'ve been conducting important market research." The boss raises an eyebrow. "What kind of market research takes two hours at a taco stand?" The employee leans forward seriously. "Competitive analysis. I\'m studying how our competitors maintain such high energy levels throughout the afternoon. Their secret appears to be generous lunch breaks, free soda refills, and not having a boss who watches them through binoculars from the third floor." The boss slowly lowers his binoculars. "You\'re either going to be fired or promoted. I haven\'t decided which yet."')

add('A teenager asks his grandmother, "Grandma, what was it like growing up without smartphones?" The grandmother puts down her knitting. "Well, let me tell you. When I wanted to talk to my friends, I had to walk to their house. In the snow. Uphill. Both ways." The teenager rolls his eyes. "Grandma, that\'s just a meme." The grandmother squints at him. "A what? Never mind, I don\'t want to know. The point is, we didn\'t need smartphones because we had something called \'going outside.\' You should try it sometime. I hear there\'s an update — now with actual sunlight." The teenager looked at his phone, then at the window, then back at his phone. "Is there a charger outside?" The grandmother sighed deeply and picked her knitting back up.')

add('A man goes to a fancy restaurant and orders the most expensive wine on the menu. The sommelier brings the bottle, shows the label, and pours a small taste. The man swirls it dramatically, smells the cork, then takes a tiny sip. He swishes it around, closes his eyes, and says, "Hmm. Notes of oak, a hint of blackberry, and... I\'m detecting a subtle undertone of... 2018 Honda Civic." The sommelier\'s eyes widen. "Sir, that\'s remarkably specific." The man sets down the glass. "That\'s because I can\'t afford this wine. I can barely afford my car payment. I was just hoping you\'d let me taste it before I order the house red." The sommelier was so impressed by the honesty that he gave him the house red for free. The man still couldn\'t afford his car payment, but at least he had a good story.')

add('A woman asks her husband, "Do you remember what today is?" The husband\'s brain goes into full panic mode. He thinks: Wedding anniversary? No, that\'s in June. Her birthday? That was three months ago. First date? He doesn\'t even remember when that was. The day they met? He\'s going to be in so much trouble. Sweat begins to form on his forehead. He blurts out, "Of course I know what today is! It\'s a very special day!" The wife smiles warmly. "It\'s Thursday." The husband exhales. "Right! Thursday! My favorite day of the week!" The wife continues, "And I was just going to ask if you wanted pizza for dinner." The husband learned nothing from this experience and would panic again next Thursday.')

add('A man is on a diet and goes to the doctor for a checkup. The doctor says, "Your weight looks good, but your cholesterol is a bit high. What have you been eating?" The man says, "Mostly salads, grilled chicken, and vegetables." The doctor looks at the chart. "Any snacks?" The man shifts uncomfortably. "Define \'snacks.\'" The doctor says, "Anything you eat between meals." The man thinks for a long moment. "Well, last night between dinner and bedtime, I had three granola bars, a bowl of ice cream, half a bag of chips, and four cookies." The doctor stares at him. "Sir, that\'s not a snack. That\'s a second dinner with dessert and an appetizer." The man nods solemnly. "I knew you were going to say that. That\'s why I also had a pre-snack snack to emotionally prepare."')

add('A teacher tells her students, "Today we\'re going to learn about irony." The class groans. One student raises his hand. "Miss, I think I already understand irony." The teacher is intrigued. "Oh really? Give me an example." The student says, "The fire station burned down yesterday." The teacher nods approvingly. "That\'s a good start. Anyone else?" Another student raises his hand. "The police station got robbed last week." The teacher is impressed. "Very good! One more?" A third student, who had been sleeping the entire class, suddenly wakes up and says, "The fact that I came to school specifically to sleep, and the one class where we learn about irony is the one class where I can\'t fall back asleep because everyone keeps yelling examples." The teacher stared at him. "That\'s... that\'s actually the best example of irony I\'ve ever heard."')

add('A little girl asks her mother, "Mommy, where do babies come from?" The mother takes a deep breath and begins the long, carefully prepared speech about birds and bees. After a lengthy and thoughtful fifteen-minute explanation, the little girl looks confused. "But Mommy, Susie at school said she came from China." The mother freezes mid-sentence. "Well, Susie is adopted, sweetheart. That\'s different." The little girl processes this for a moment. "So some babies come from storks, some come from China, and some come from biology class?" The mother closed her eyes. "Yes, sweetie. It\'s a very complicated global supply chain. Now please go watch cartoons."')

add('A husband is reading a book in bed. His wife comes out of the bathroom wearing a new nightgown. She asks, "Honey, do you notice anything different?" The husband looks up from his book, scans her quickly, and says, "New haircut?" She shakes her head. "New earrings?" She crosses her arms. "Makeup?" She grabs the book from his hands. "I\'m wearing a completely new outfit I bought today, and I\'ve been standing here for thirty seconds!" The husband looks at her seriously and says, "Honey, I have a PhD in not noticing things. It\'s not that I don\'t love you. It\'s that my brain processes information on a significant delay. Give me three to five business days, and I promise I\'ll compliment your new nightgown." The wife threw a pillow at him. He caught it, which proved he could notice some things — just not the right ones.')

add('A man walks into a pet store and says, "I want to buy a parrot that can talk." The shopkeeper points to a beautiful green parrot. "This one knows over 200 words and phrases." The man asks, "How much?" The shopkeeper says, "$500." The man then points to a scruffy-looking parrot in the corner. "What about that one?" The shopkeeper says, "That one is $1,000." The man is confused. "Why? He looks terrible!" The shopkeeper lowers his voice. "That parrot doesn\'t say a single word, but the other parrot calls him \'Boss.\'" The man nodded thoughtfully. "I\'ll take both. I\'m starting a company and I need a CEO and an employee who actually does all the work."')

add('A priest, a minister, and a rabbit walk into a blood bank. The nurse asks the rabbit, "What\'s your blood type?" The rabbit looks confused and says, "I think I\'m a Type O." The priest and minister exchange confused looks. The minister whispers, "I didn\'t know rabbits could talk." The rabbit turns to them and says, "I didn\'t know this was a joke about religion. I thought it was a joke about blood types. Can we just donate and leave?" The nurse, without missing a beat, hands the rabbit a form and says, "Sir, you have to fill this out first. And I\'m going to need to see some identification, because I don\'t think rabbits are legally allowed to donate blood." The rabbit pulls out a tiny driver\'s license. Everyone in the room decided to just go with it.')

add('An IT support technician gets a call. "My computer won\'t turn on." The technician asks, "Is it plugged in?" The caller says, "Of course it\'s plugged in! What do you think I am, an idiot?" The technician apologizes and spends the next forty-five minutes troubleshooting. He remotes into the machine, checks the power settings, runs diagnostics, updates drivers, and even does a system restore. Nothing works. Finally, the technician says, "Can you just check the power cord one more time?" There\'s a pause. Then the caller says, "Oh. The power strip was turned off." The technician stares at the ceiling for a full minute. "No problem, sir. That\'s why we\'re here. Have a great day." He then muted his microphone and screamed into a pillow for exactly seven seconds before answering the next call.')

add('A wife texts her husband: "Come home quickly. There\'s a huge spider in the bathroom!" The husband texts back: "How huge?" The wife sends a photo with a ruler next to the spider. The husband texts back: "That\'s 3 centimeters. You can handle that." There\'s a long pause. Then the wife sends another photo. The ruler now has bite marks in it. The husband was home in seven minutes, which he later admitted was a personal record. The spider, by the time he arrived, had relocated to an undisclosed location somewhere in the laundry basket. The husband spent the next hour removing every piece of clothing one by one with barbecue tongs while the wife stood on the bed providing emotional support from a safe distance.')

add('A man is at a coffee shop and the barista asks, "Can I get a name for your order?" The man says, "Sure, it\'s \'Batman.\'" The barista writes it down without looking up. A few minutes later, the barista calls out, "Venti caramel macchiato for... Batman?" The man walks up and takes his drink. A little boy at the next table tugs on his mom\'s sleeve. "Mommy, Batman drinks caramel macchiatos!" His mom whispers, "Sweetie, that\'s not the real Batman." The man turns around, takes a sip of his macchiato, and says in a deep voice, "The real Batman is currently fighting crime. I\'m his cousin, Cappuccino Man. I handle the caffeine-related emergencies." The little boy\'s eyes went wide. The mother mouthed "thank you" to the man, who tipped his invisible cape and walked out into the afternoon, feeling like an actual superhero.')

add('A husband asks his wife, "Why do women always go to the bathroom in groups?" The wife puts down her magazine. "That\'s a great question, honey. It\'s because we\'re discussing a top-secret global conspiracy to take over the world, and the bathroom is the only place men won\'t follow us." The husband laughs nervously. "You\'re joking, right?" The wife smiles sweetly. "Of course I\'m joking. The conspiracy meetings are actually in the kitchen. The bathroom trips are just for gossiping about how cute the waiter is." The husband didn\'t sleep well that night. Not because of the conspiracy, but because he spent four hours trying to figure out which waiter his wife was talking about.')

add('A teacher says to her class, "I want everyone to raise their hand if they think they\'re stupid." After a long silence, little Jimmy slowly raises his hand. The teacher looks surprised. "Jimmy, why do you think you\'re stupid?" Jimmy sighs dramatically. "I don\'t think I\'m stupid, Miss. I just felt bad that you were standing there all alone." The teacher\'s mouth opened and closed several times. The rest of the class turned to look at Jimmy with a mixture of horror and admiration. Jimmy received detention, but he also received a standing ovation from his classmates. He later went on to become a very successful lawyer who specialized in technically-not-wrong arguments.')

add('A man is pulled over by a police officer. The officer says, "Sir, do you know why I pulled you over?" The man says, "Because I was speeding?" The officer says, "No. Because you were driving too slow." The man looks confused. "Too slow?" The officer nods. "You were going 25 in a 65 zone. What\'s going on?" The man sighs deeply. "My mother-in-law is in the back seat, and she told me to drive carefully." The officer looks in the back seat and sees no one. "Sir, there\'s no one there." The man\'s face drops. "Oh no. I dropped her off at the airport two hours ago." The officer paused, walked back to his patrol car, and radioed his supervisor. "Dispatch, I\'ve got a situation here. The driver is technically not speeding, but I think he\'s going through something way worse than a speeding ticket."')

add('A woman is trying to assemble a piece of IKEA furniture. Her husband walks in and says, "Do you need help? I\'ve assembled furniture before." The woman, surrounded by scattered screws, wooden panels, and an instruction manual that appears to have been designed by a sadist, says, "No, I\'m fine. This is a one-person job." The husband sits down and watches. Ten minutes pass. Twenty minutes. At the thirty-minute mark, the wife looks up and says, "Why is this so hard? The instructions just show a happy cartoon person putting it together in three steps!" The husband peers at the manual. "Honey, that\'s the cover of the instruction manual. The actual instructions are the next forty-seven pages." The wife stared at him for a long time. "I knew that. I was just testing you." She then handed him the screwdriver and went to order takeout.')

add('A man goes to his therapist and says, "Doc, I have a problem. Every night I dream that I\'m a parking meter." The therapist nods thoughtfully. "That\'s an unusual dream. What happens in these dreams?" The patient says, "Nothing much. I just stand there. Cars pull up. People put coins in me. It\'s actually quite peaceful." The therapist asks, "So what\'s the problem?" The patient leans forward and whispers, "I think my wife is cheating on me with a fire hydrant." The therapist put down his notebook. "I\'m sorry, I\'m going to need you to repeat that." The patient nodded solemnly. "I know how it sounds. But last night in my dream, I saw them together. She was putting quarters in him. That\'s MY job.')

add('A boss tells his team, "We need to cut costs by 30 percent this quarter. Any ideas?" An employee raises his hand. "We could cancel the expensive team-building retreat." The boss shakes his head. "No, that\'s essential for morale." Another employee says, "We could reduce office supply spending." The boss says, "No, we need those supplies." A third employee, who had been quietly listening, speaks up. "What if we reduced the number of unnecessary meetings?" The room goes completely silent. The boss stares at him. "That\'s the most radical thing I\'ve ever heard. Let\'s schedule a meeting to discuss it. We\'ll need about four hours. Everyone clear your calendars." They scheduled the meeting for the following week. At that meeting, they scheduled another meeting. The costs were never cut.')

add('A teenager asks his father, "Dad, what\'s the difference between a friend and a best friend?" The father puts down his tools. "Well, son, a friend will help you move a couch. A best friend will help you move a body." The teenager\'s eyes go wide. "Dad, that\'s dark." The father laughs. "I\'m kidding! I\'m kidding!" He pauses. "A best friend will actually help you move BOTH couches. The bodies are a separate arrangement. You need a different level of friendship for that." The teenager stared at his father. "I have so many questions." The father patted him on the shoulder. "And I have so few answers. That\'s what makes our relationship special."')

add('A husband tells his wife, "I think you\'re spending too much time on your phone." The wife doesn\'t look up from her phone. "That\'s interesting." The husband continues, "I feel like you love your phone more than me." The wife scrolls for a few more seconds, then holds up a finger. "Hold on. I\'m just reading an article about how to deal with husbands who complain about phone usage." The husband sighs. "And what does it say?" The wife finally looks up and smiles. "It says I should put down my phone and give you my full attention. But that was five paragraphs ago, and since then I\'ve also read three recipes, a news article, and a Facebook post from someone I haven\'t spoken to since high school about their new puppy." The husband nodded slowly. "At least the puppy was cute?" The wife showed him the picture. It was, indeed, an incredibly cute puppy. The argument was over. The puppy had won.')

add('A man is at the DMV waiting for his number to be called. He looks at his ticket. Number 847. He looks at the display. "Now serving: 12." A man next to him chuckles. "First time? I\'ve been here so long I\'ve memorized the ceiling tiles. There are exactly 238. Three of them are slightly discolored. Those three are my favorites." The first man stares at him. "How long have you been here?" The second man looks at his watch. "It\'s hard to say. I came in during the previous presidential administration. I think I was in my twenties. I\'m now a grandfather of three." Just then, the display changes to 13. A cheer goes up across the room. It was the most excitement anyone had seen at the DMV since 1997 when someone\'s paperwork was actually processed correctly on the first try.')

add('A wife says to her husband, "Let\'s play a game. I\'ll name three things, and you tell me what they have in common." The husband agrees. "Okay, hit me." The wife says, "My mother, a hurricane, and a detective." The husband thinks for a moment. "They all... show up unannounced?" The wife gasps. "How did you know?!" The husband says, "Because your mother showed up last week and stayed for four days. I didn\'t know she was coming until she was already in the kitchen reorganizing our cabinets." The wife nods. "That\'s fair. But what about the hurricane and the detective?" The husband says, "The hurricane was the aftermath of your mother\'s visit, and the detective is who I was planning to hire to find out where all our snacks went." The wife stared at him. "You\'ve thought about this a lot." The husband nodded grimly. "Four days, honey. Four days."')

add('A man is at the doctor. "Doctor, it hurts when I do this." He raises his arm above his head. The doctor looks at him. "Then don\'t do that." The man stares. "That\'s your medical advice? Don\'t do that?" The doctor nods. "Yes. That\'ll be two hundred dollars." The man starts to protest, but the doctor holds up a hand. "Sir, I spent eight years in medical school and accumulated two hundred thousand dollars in student loan debt to be able to tell you that exact sentence. You\'re not paying me for the four words. You\'re paying me for knowing which four words to say." The man thought about this for a moment, then raised his arm above his head again. "Ow." The doctor sighed and handed him a pamphlet titled "Learning to Listen: A Guide for Patients Who Don\'t Follow Simple Instructions."')

add('A father takes his teenage daughter to her first driving lesson. She gets in the car, adjusts the mirrors, fastens her seatbelt, and turns on the engine. "Okay, Dad. Ready!" The father, gripping the door handle tightly, says, "Remember, the brake is on the left." The daughter looks at him. "Dad, the brake is on the left? I thought the brake was on the right." The father\'s face goes pale. "No, sweetheart. The gas is on the right. The brake is on the left." The daughter thinks for a moment. "Are you sure? Because in that movie we watched last week, the bad guy was driving with his left foot." The father turns off the engine and takes the keys out. "Lesson\'s over. We\'re trying again when you\'re twenty-five." The daughter protested, but the father had already made up his mind. He walked home and left the car parked there for three days.')

add('A boss asks an employee, "Why did you come in late today?" The employee says, "I\'m sorry, sir. I was up all night worrying about the quarterly report. Then I overslept. Then my alarm didn\'t go off. Then my car wouldn\'t start. Then I had to take the bus. Then the bus got stuck in traffic. Then—" The boss holds up a hand. "Stop. Let me guess. Then a meteor hit the bus?" The employee brightens. "Actually, sir, it was a small asteroid. But close!" The boss stares at him for a full ten seconds. "I want you to know that I\'m not firing you today." The employee looks relieved. "Thank you, sir!" The boss continues, "Not because I believe your story. But because it\'s the most creative excuse I\'ve heard in twenty years of management, and I want to hear what you come up with next time."')

add('A mother is helping her son with his math homework. "If you have 10 chocolates and someone asks for 3, how many do you have left?" The son thinks carefully. "10." The mother sighs. "No, sweetie. 10 minus 3 is 7." The son shakes his head confidently. "No, Mom. I would say I have 7, but I would actually still have 10. Because if someone asks me for chocolate, I\'m not giving them any." The mother calls her husband. "Your son refuses to do subtraction because of strategic snack hoarding." The father calls back, "That\'s my boy! Teach him about taxes next!" The mother hung up and stared at the ceiling. "I\'m surrounded by financial masterminds and none of them can do basic arithmetic."')

add('A woman at a restaurant waves down the waiter. "Excuse me, I ordered my steak well-done." The waiter looks at her plate. "Yes, ma\'am. That is well-done." The woman points at the steak. "This steak is so well-done that it\'s practically a hockey puck. I could play an entire NHL game with this steak." The waiter leans in and examines the steak. "Ma\'am, with all due respect, our chef is not responsible for your decision to order a premium cut of beef cooked to the consistency of a car tire. If you\'d like, I can bring you a new steak, but I must warn you — it will also be well-done, and it will also be a hockey puck, because that is the nature of well-done steak." The woman stared at him. "Are you a waiter or a philosopher?" The waiter replied, "After five years in this industry, ma\'am, there is no difference."')

add('A man tells his friend, "I\'m going to start a podcast." His friend asks, "What\'s it about?" The man says, "I\'m going to interview experts about their deepest darkest secrets." The friend looks skeptical. "Do you know any experts?" The man shakes his head. "That\'s the beauty of it. Neither do the listeners." The friend is confused. "How does that work?" The man explains, "I just find people who sound very confident on the internet and let them talk for two hours. By the time the listener realizes they\'re not experts, they\'ve already invested too much time to quit." The friend nodded slowly. "So it\'s like a Ponzi scheme, but for attention spans." The man pointed at him. "That\'s going to be the title of our first episode. You\'re my first guest." The friend immediately regretted ever speaking.')

add('A wife texts her husband: "Bring home milk." The husband replies: "What kind?" The wife: "The regular kind." The husband, standing in the dairy aisle, stares at the wall of milk options. Whole milk. Two percent. One percent. Skim. Almond milk. Oat milk. Soy milk. Coconut milk. Lactose-free milk. He texts back: "Please define regular." The wife: "The kind we always get." The husband: "I don\'t know what kind we always get because you always buy it." The wife: "Then just get whatever." The husband: "That\'s exactly what I was trying to avoid." He bought oat milk because the carton looked friendly. When he got home, his wife took one look and said, "Why did you buy oat milk? We always get almond." The husband slept on the couch that night, not as punishment, but because he needed time alone to process the events of the dairy aisle.')

add('A man is in an important video call when his cat walks across the keyboard. "Sorry, everyone," he says. "That was just my cat." His cat then proceeds to sit directly in front of the camera, blocking the man\'s face entirely. "Mrrp," says the cat. The client on the other end says, "I\'m sorry, I can\'t see you. There appears to be a... furry obstruction." The man lifts his cat off the desk. The cat immediately jumps back up and sits down again. This happens three more times. Finally, the client says, "You know what, let\'s just put the cat on the project. It seems very committed." The cat got a promotion before the man did. Six months later, the client still referred to the cat as "our best consultant." The man was both proud and deeply insulted.')

add('A father is trying to teach his son how to ride a bike. "Pedal, pedal, pedal! Balance! You\'ve got this!" The son wobbles and crashes into a bush. The father runs over. "Are you okay?" The son, covered in leaves, looks up at his father. "Dad, I\'ve been thinking. Why do we need bikes when we have cars?" The father says, "Because bikes are good exercise and they\'re fun." The son squints at him. "Fun? I just flew into a bush. If I was in a car, there would be airbags. Did the bike have airbags? No. I rest my case." The father stared at his seven-year-old lawyer. "You\'re going to be a difficult teenager." The son got up and dusted himself off. "Jury\'s still out on that one, Dad. Now push me again. I\'m aiming for the mailbox this time."')

# ── Generate 300 posts ──────────────────────────────────────────
print('Generating 300 English joke posts...')
posts = []

for i in range(300):
    base = random.choice(title_templates)
    suffix_num = i + 1
    suffix_variants = [
        f' (Part {suffix_num})', f' Vol. {suffix_num}', f' Edition {suffix_num}',
        f' #{suffix_num}', f' Collection {suffix_num}',
        f' Series {suffix_num}', f' Chapter {suffix_num}',
    ]
    title = base + random.choice(suffix_variants)
    if len(title) > 50:
        title = title[:47] + '...'
    while len(title) < 16:
        title = title + '!'

    # Combine 1-3 jokes
    joke_pool = random.sample(jokes, min(len(jokes), random.randint(1, 3)))
    content = '\n\n'.join(joke_pool)
    if len(content) > 1000:
        content = content[:997] + '...'
    elif len(content) < 300:
        extra = random.choice([j for j in jokes if j not in joke_pool])
        content = content + '\n\n' + extra
        if len(content) > 1000:
            content = content[:997] + '...'

    posts.append(Post(title=title, content=content, author=author))

Post.objects.bulk_create(posts)
print(f'Created {Post.objects.count()} posts')

from django.db.models import Avg, Min, Max, Count
from django.db.models.functions import Length
s = Post.objects.aggregate(
    c=Count('id'),
    at=Avg(Length('title')), it=Min(Length('title')), xt=Max(Length('title')),
    ac=Avg(Length('content')), ic=Min(Length('content')), xc=Max(Length('content')),
)
print(f'Total:   {s["c"]}')
print(f'Title:   avg={s["at"]:.0f}  min={s["it"]}  max={s["xt"]}')
print(f'Content: avg={s["ac"]:.0f}  min={s["ic"]}  max={s["xc"]}')

p = Post.objects.order_by('?').first()
print(f'\nSample Title ({len(p.title)}c): {p.title}')
print(f'Sample Content ({len(p.content)}c): {p.content[:120]}...')
